version: "3"

services:
  localstack:
    container_name: localstack_gitops
    image: localstack/localstack:0.12.16
    ports:
      - "4566:4566"
    environment:
      - AWS_ACCESS_KEY_ID=mock
      - AWS_SECRET_ACCESS_KEY=mock
      - EDGE_PORT=4566
      - DEFAULT_REGION=us-east-1
      - SERVICES=s3
    volumes:
      - "./.localstack:/tmp/localstack"
      # - "./localstack:/docker-entrypoint-initaws.d"
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - localstack

networks:
  localstack:
    driver: bridge